version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        SECRET_KEY: ${SECRET_KEY}
        DJANGO_DEBUG: ${DJANGO_DEBUG}
    container_name: django_app
    # command: /code/paracord_runner.sh
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --log-level info shop.wsgi:application    
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - redis
    environment:
      - DEBUG=${DJANGO_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    networks:
      - mynetwork
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
