# Generated by Django 5.0.9 on 2024-09-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_categories_options_alter_categories_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ("-discount",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=4,
                verbose_name="Discount in %",
            ),
        ),
    ]
