# Generated by Django 5.0.9 on 2024-09-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_products_options_alter_products_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="qunatity",
            new_name="quantity",
        ),
    ]
