# Generated by Django 5.0.9 on 2024-09-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_rename_qunatity_products_quantity"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderTime",
            new_name="OrderItem",
        ),
    ]
